import { NextRequest, NextResponse } from "next/server";
import { validateSessionToken, COOKIE_NAME } from "@/lib/admin-auth";
import fs from "node:fs";
import path from "node:path";
import cloudinary, { CLOUDINARY_FOLDER } from "@/lib/cloudinary";

async function isAuthenticated(request: NextRequest): Promise<boolean> {
  const cookie = request.cookies.get(COOKIE_NAME);
  if (!cookie?.value) return false;
  return validateSessionToken(cookie.value);
}

// Read from pre-built manifest (generated by prebuild script)
function getManifest(): { images: string[]; grouped: Record<string, string[]>; total: number } | null {
  try {
    const manifestPath = path.join(process.cwd(), "content", "image-manifest.json");
    if (fs.existsSync(manifestPath)) {
      return JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
    }
  } catch {
    // Manifest not available — fall through to live scan
  }
  return null;
}

// Live scan fallback for development
function scanImages(): { images: string[]; grouped: Record<string, string[]>; total: number } {
  const extensions = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);
  const publicDir = path.join(process.cwd(), "public");
  const imagesDir = path.join(publicDir, "images");

  function recurse(dir: string): string[] {
    const results: string[] = [];
    if (!fs.existsSync(dir)) return results;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        results.push(...recurse(full));
      } else if (extensions.has(path.extname(entry.name).toLowerCase())) {
        results.push("/" + path.relative(publicDir, full).replaceAll("\\", "/"));
      }
    }
    return results;
  }

  const images = recurse(imagesDir);
  const grouped: Record<string, string[]> = {};
  for (const img of images) {
    const parts = img.split("/");
    const category = parts[2] || "other";
    if (!grouped[category]) grouped[category] = [];
    grouped[category].push(img);
  }

  return { images, grouped, total: images.length };
}

// Fetch images from Cloudinary
async function getCloudinaryImages(): Promise<{ images: string[]; grouped: Record<string, string[]> }> {
  const images: string[] = [];
  const grouped: Record<string, string[]> = {};

  try {
    let nextCursor: string | undefined;
    do {
      const result = await cloudinary.api.resources({
        type: "upload",
        prefix: CLOUDINARY_FOLDER,
        max_results: 500,
        next_cursor: nextCursor,
      });

      for (const resource of result.resources) {
        const url = resource.secure_url as string;
        images.push(url);

        // Extract folder name for grouping: myvisualspace/hero/img -> "hero (cloud)"
        const parts = (resource.public_id as string).split("/");
        const folder = parts.length > 1 ? parts[1] : "uploads";
        const groupKey = `${folder} (cloud)`;
        if (!grouped[groupKey]) grouped[groupKey] = [];
        grouped[groupKey].push(url);
      }

      nextCursor = result.next_cursor;
    } while (nextCursor);
  } catch {
    // Cloudinary unavailable — return empty
  }

  return { images, grouped };
}

// GET /api/admin/images — List all images (local + Cloudinary)
export async function GET(request: NextRequest) {
  if (!(await isAuthenticated(request))) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Get local images from manifest or filesystem scan
  const local = getManifest() || scanImages();

  // Get Cloudinary images
  const cloud = await getCloudinaryImages();

  // Merge both sources
  const allImages = [...local.images, ...cloud.images];
  const allGrouped = { ...local.grouped, ...cloud.grouped };

  return NextResponse.json({
    images: allImages,
    grouped: allGrouped,
    total: allImages.length,
  });
}
